api = "0.9"

[buildpack]
id = "heroku/apt"
version = "0.0.1"
name = "Heroku Apt"
description = "Heroku's Apt buildpack"
homepage = "https://github.com/heroku/buildpacks-apt"
keywords = ["apt"]

[[buildpack.licenses]]
type = "ALv2"

[[stacks]]
id = "*"

[metadata.release]
image = { repository = "docker.io/heroku/buildpacks-apt" }
