[package]
name = "buildpacks-apt"
version = "0.1.0"
edition = "2021"
rust-version = "1.75"

[dependencies]
commons = { git = "https://github.com/heroku/buildpacks-ruby", branch = "main" }
fun_run = "0.1"
indoc = "2"
libcnb = { version = "=0.17.0", features = ["trace"] }
regex-lite = "0.1"
semver = "1"
serde = "1"
tempfile = "3"

[dev-dependencies]
libcnb-test = "=0.17.0"
indoc = "2"

[profile.release]
strip = true