[package]
name = "buildpacks-apt"
version = "0.1.0"
edition = "2021"
rust-version = "1.75"

[dependencies]
commons = { git = "https://github.com/heroku/buildpacks-ruby", branch = "main" }
libcnb = { version = "=0.17.0", features = ["trace"] }
serde = "1"

[dev-dependencies]
libcnb-test = "=0.17.0"
indoc = "2"

[profile.release]
strip = true